### ISSUE TITLE
[Questions] an alternative for coffee script

### ISSUE THREAD

**Issue by binhgo** [imachug/ZeroLib#2]
Do you know any alternative for coffee script, currently I cannot build it using CF 2. or CF 1.1. So I have to edit the code directly on all.js file which is quite messy.

And Nice to meet you, I am also a fan of zeronet.

**Comment by purplesyringa** [comment]
ZeroNet supports both CoffeeScript and JavaScript. To make this library work, just copy the files you need to e.g. "js/zero-dev-lib", and then change "index.html", like this:

```html
<script src="js/zero-dev-lib/ZeroPage.js"></script>
...
```

Hope this helps.

**Comment by binhgo** [comment]
Thanks Pro, 
I am reading your tutorial, really helpful. I can now understand more thing with your tutorial.
Do you have any contact? Just want to talk to you more, I really love this Zeronet, and want to build a site for my country :-)

**Comment by purplesyringa** [comment]
I love ZeroNet as well. If you need my contacts, you can use ZeroMail (though I can't tell I read it that often) - gitcenter@zeromail.bit, or my email - imachug [@] g mail [point] com.
