### ISSUE TITLE
[Enhancement] Allow to write and read binary and non-encoded text files

### ISSUE THREAD

**Issue by trenta3** [imachug/ZeroLib#3]
I see that in `ZeroFS.js` all read and written files are base64 encoded.

Please also support the following:
- [x] Text files (as it is now, without the base64 encoding)
- [ ] Gzipped base64 encoded files to save space
- [x] Binary files using the `FileReader` methods

**Comment by purplesyringa** [comment]
Unfortunately, the `Text files` part won't work because base64 encoding is needed for writing. However, other points are fair -- I'll implement them (I hope) soon.

**Comment by trenta3** [comment]
Are you absolutely sure? Why do you say so?
Even if one knows he is always writing out text-only files or json content like the following:

```
{
  "posts": [
    { "title": "Example", "body": "Content" },
    { "title": "Test", "body": "Contetn" }
  ]
}
```

**Comment by purplesyringa** [comment]
Then I probably didn't understand you. Can you please explain? What I mean is that the resulting files are JSON/text, not base64.

**Comment by trenta3** [comment]
Ok, I realized now that the [official documentation](https://zeronet.readthedocs.io/en/latest/site_development/zeroframe_api_reference/#filewrite-inner_path-content) explicitly says that `fileWrite` needs base64 encoded content, but I'm sure I've always passed to it `text/JSON` content and it worked fine, so I'm now a bit confused if passing base64-encoded text writes the decoded string to the file or if simply writes what is passed to it.

**Comment by purplesyringa** [comment]
If you pass a base64-encoded string to fileWrite, the original string is written to the disk.

**Comment by purplesyringa** [comment]
I'm closing this as this issue seams like resolved, fell free to reopen it if you still have questions.

**Comment by danimesq** [comment]
@trenta3 
Please mark all checkboxes if they are fixed.
